# ===================================================================
# Spring Boot configuration for the "qualif" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jmx:
      default-domain: '@jmx-default-namespace@'
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    data:
        cassandra:
            contactPoints: s00vl9962302,s00vl9962303,s00vl9962591,s00vl9962314
            compression: LZ4
            keyspaceName: cj_propertyloan
            port: 1521
            username: dev_cj_propertyloan
            password: W5_ONwCDyYPN24J
            cluster-name: DC_OLTP_BDDF_QUAL_1
            ssl: true
            consistency-level: LOCAL_QUORUM
    cache:
        hosts: s00vl9969502,s00vl9969511
        port: 5701
        portCount: 100
        
### Config of the SMTP server        
    mail:
          host: vip-smtp-staging-echonet.fr.net.intra
          port: 25
          properties:
                mail.smtp:
                          connectiontimeout: 5000
                          timeout: 5000
                          writetimeout: 5000  
    sleuth:
            enabled: true
            log:
                slf4j:
                    enabled: true
logging:
    config: classpath:logback-qualif.xml
    file: /applis/logs/12243-hpl00/wlc/sa-12243_hpl00_propertyloan-biz-3/sa-12243_hpl00_propertyloan-biz-3/logs/sm-12243_hpl00.log
    pattern:
        file: '%date{yyyy-MM-dd HH:mm:ss.SSSXXX} | %-5level | %X{HostName} | %X{IP} | %X{AppName},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-} | %X{JMSCorrelationID} | %X{JMSTimeHandledMessage} | %X{UserID} | %X{Marker} | %logger{36} - %msg%n'
        console: '%date{yyyy-MM-dd HH:mm:ss.SSSXXX} | %-5level | %X{HostName} | %X{IP} | %X{AppName},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-} | %X{JMSCorrelationID} | %X{JMSTimeHandledMessage} | %X{UserID} | %X{Marker} | %logger{36} - %msg%n'

server:
    port: 10081
    dnsHostName: exp-srv-metier-s1-rhel66.staging.echonet
         
jms:
  mq:
    hosts: s00vl9973150(48681),s00vl9973159(48681)
    queue-manager: FRHPL01Z
    channel: CLIHPL01.FRHPL01Z.T1
    receive-timeout: 2000
    inbound-default-queue: CREIMO
    outbound-default-queue: CREDIT.IMMOBILIER
    outbound-virtuo-queue: VIRTUO
    queue-notification: queue:///CREIMO.NOTIF?targetClient=1
      
#
# Eureka
#
ribbon:
  IsSecured: true
  eureka:
    enabled: true    
eureka:  
  client:
    serviceUrl:
      # For multiple eureka instances use ',' separator : https://exp-srv-metier-s1-rhel66.staging.echonet:10448/eureka,https://exp-srv-metier-s2-rhel66.staging.echonet:10448/eureka
      defaultZone: https://exp-srv-metier-s1-rhel66.staging.echonet:10448/eureka,https://exp-srv-metier-s2-rhel66.staging.echonet:10448/eureka
  instance:
    hostname: ${server.dnsHostName}
    nonSecurePortEnabled: false
    non-secure-port: ${server.port}
    securePortEnabled: true
    secure-port: 10444
    instance-id: ${server.dnsHostName}:${spring.application.name}:${spring.application.instance_id:${eureka.instance.secure-port}}
    health-check-url: https://${server.dnsHostName}:${eureka.instance.secure-port}${management.context-path}/health
    status-page-url: https://${server.dnsHostName}:${eureka.instance.secure-port}${management.context-path}/info
    home-page-url: https://${server.dnsHostName}:${eureka.instance.secure-port}

#### Email collab ########################
collaborator:
      mail:
        sender: buymyhome@pilot.fr
        recipient: buymyhome@pilot.fr

###########OpeGoal########################
numeratorUri: https://goalgateway.staging.echonet/goal-json-gateway/defimmo_num.1.0/defimmo_numertr
rchPrsneKpiUrl: https://goalgateway.staging.echonet/goal-json-gateway/recup_prsne_kpi.1.0/rch_prsne_kpi
calTarAssUrl: https://goalgateway.staging.echonet/goal-json-gateway/cal_tar_ass.1.0/mzimta10
defiImmoUri: https://goalgateway.staging.echonet/goal-json-gateway/s_d_enrg_plr.1.0/o_d_enrg_plr
rg.directive.url: https://interaction.staging.echonet:443/ZIM/defi-immo-directive-webapp/service/handle

            
########## MAESTRO #######################
maestro:
    path: /applis/12243-hpl00/transfer/in/
    target.path: /applis/12243-hpl00/transfer/in/out/
    file.name: ExportListPj
    cron.date.launcher: 0 0 18 * * *
    cron.date.launcher.delete: '0 0 12 * * ?'
    daysbetween: 90
collect:
    cron.date.launcher: 0 0 0 1/1 * ?