# ===================================================================
# Spring Boot configuration for the "mock" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: mock
        include: swagger          
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false

logging:
    config: classpath:logback-local.xml
    
server:
    port: 10081

eureka:
  client:
    serviceUrl:
      defaultZone: http://s00vl9966976.fr.net.intra:10083/eureka
    
